import requests
import json
import os
from datetime import datetime

RAPIDAPI_KEY = os.environ.get("RAPIDAPI_KEY", "")

PLAYER_MAP = {
  "1629638": {"name": "Nickeil Alexander-Walker", "team": "ATLANTA HAWKS"},
  "1628396": {"name": "Tony Bradley", "team": "ATLANTA HAWKS"},
  "1630700": {"name": "Dyson Daniels", "team": "ATLANTA HAWKS"},
  "1642484": {"name": "RayJ Dennis", "team": "ATLANTA HAWKS"},
  "1631243": {"name": "Mouhamed Gueye", "team": "ATLANTA HAWKS"},
  "1627741": {"name": "Buddy Hield", "team": "ATLANTA HAWKS"},
  "1630552": {"name": "Jalen Johnson", "team": "ATLANTA HAWKS"},
  "1630557": {"name": "Corey Kispert", "team": "ATLANTA HAWKS"},
  "1631132": {"name": "Christian Koloko", "team": "ATLANTA HAWKS"},
  "1630228": {"name": "Jonathan Kuminga", "team": "ATLANTA HAWKS"},
  "1629111": {"name": "Jock Landale", "team": "ATLANTA HAWKS"},
  "203468":  {"name": "CJ McCollum", "team": "ATLANTA HAWKS"},
  "1642854": {"name": "Asa Newell", "team": "ATLANTA HAWKS"},
  "1627777": {"name": "Georges Niang", "team": "ATLANTA HAWKS"},
  "1630168": {"name": "Onyeka Okongwu", "team": "ATLANTA HAWKS"},
  "1642258": {"name": "Zaccharie Risacher", "team": "ATLANTA HAWKS"},
  "1629216": {"name": "Gabe Vincent", "team": "ATLANTA HAWKS"},
  "1630811": {"name": "Keaton Wallace", "team": "ATLANTA HAWKS"},
  "1627759": {"name": "Jaylen Brown", "team": "BOSTON CELTICS"},
  "1630568": {"name": "Luka Garza", "team": "BOSTON CELTICS"},
  "1642864": {"name": "Hugo González", "team": "BOSTON CELTICS"},
  "1631199": {"name": "Ron Harper Jr.", "team": "BOSTON CELTICS"},
  "1630573": {"name": "Sam Hauser", "team": "BOSTON CELTICS"},
  "1630202": {"name": "Payton Pritchard", "team": "BOSTON CELTICS"},
  "1629674": {"name": "Neemias Queta", "team": "BOSTON CELTICS"},
  "1631248": {"name": "Baylor Scheierman", "team": "BOSTON CELTICS"},
  "1642917": {"name": "Max Shulga", "team": "BOSTON CELTICS"},
  "1628369": {"name": "Jayson Tatum", "team": "BOSTON CELTICS"},
  "1642910": {"name": "John Tonje", "team": "BOSTON CELTICS"},
  "202696":  {"name": "Nikola Vučević", "team": "BOSTON CELTICS"},
  "1641775": {"name": "Jordan Walsh", "team": "BOSTON CELTICS"},
  "1628401": {"name": "Derrick White", "team": "BOSTON CELTICS"},
  "1642873": {"name": "Amari Williams", "team": "BOSTON CELTICS"},
  "1628386": {"name": "Jarrett Allen", "team": "CLEVELAND CAVALIERS"},
  "1628418": {"name": "Thomas Bryant", "team": "CLEVELAND CAVALIERS"},
  "1631165": {"name": "Keon Ellis", "team": "CLEVELAND CAVALIERS"},
  "201935":  {"name": "James Harden", "team": "CLEVELAND CAVALIERS"},
  "1630241": {"name": "Sam Merrill", "team": "CLEVELAND CAVALIERS"},
  "1642434": {"name": "Riley Minix", "team": "CLEVELAND CAVALIERS"},
  "1628378": {"name": "Donovan Mitchell", "team": "CLEVELAND CAVALIERS"},
  "1630596": {"name": "Evan Mobley", "team": "CLEVELAND CAVALIERS"},
  "1626204": {"name": "Larry Nance Jr.", "team": "CLEVELAND CAVALIERS"},
  "1641854": {"name": "Craig Porter Jr.", "team": "CLEVELAND CAVALIERS"},
  "1642878": {"name": "Tyrese Proctor", "team": "CLEVELAND CAVALIERS"},
  "203471":  {"name": "Dennis Schröder", "team": "CLEVELAND CAVALIERS"},
  "1629622": {"name": "Max Strus", "team": "CLEVELAND CAVALIERS"},
  "1641772": {"name": "Nae'Qwan Tomlin", "team": "CLEVELAND CAVALIERS"},
  "1642281": {"name": "Jaylon Tyson", "team": "CLEVELAND CAVALIERS"},
  "1629731": {"name": "Dean Wade", "team": "CLEVELAND CAVALIERS"},
  "1631128": {"name": "Christian Braun", "team": "DENVER NUGGETS"},
  "1628971": {"name": "Bruce Brown", "team": "DENVER NUGGETS"},
  "203932":  {"name": "Aaron Gordon", "team": "DENVER NUGGETS"},
  "203501":  {"name": "Tim Hardaway Jr.", "team": "DENVER NUGGETS"},
  "1641747": {"name": "DaRon Holmes II", "team": "DENVER NUGGETS"},
  "1629661": {"name": "Cameron Johnson", "team": "DENVER NUGGETS"},
  "203999":  {"name": "Nikola Jokić", "team": "DENVER NUGGETS"},
  "1642938": {"name": "Curtis Jones", "team": "DENVER NUGGETS"},
  "1642461": {"name": "Spencer Jones", "team": "DENVER NUGGETS"},
  "1626145": {"name": "Tyus Jones", "team": "DENVER NUGGETS"},
  "1627750": {"name": "Jamal Murray", "team": "DENVER NUGGETS"},
  "1630192": {"name": "Zeke Nnaji", "team": "DENVER NUGGETS"},
  "1629618": {"name": "Jalen Pickett", "team": "DENVER NUGGETS"},
  "1642354": {"name": "KJ Simpson", "team": "DENVER NUGGETS"},
  "1631124": {"name": "Julian Strawther", "team": "DENVER NUGGETS"},
  "202685":  {"name": "Jonas Valančiūnas", "team": "DENVER NUGGETS"},
  "1631212": {"name": "Peyton Watson", "team": "DENVER NUGGETS"},
  "1630595": {"name": "Cade Cunningham", "team": "DETROIT PISTONS"},
  "1631105": {"name": "Jalen Duren", "team": "DETROIT PISTONS"},
  "1629750": {"name": "Javonte Green", "team": "DETROIT PISTONS"},
  "202699":  {"name": "Tobias Harris", "team": "DETROIT PISTONS"},
  "1641842": {"name": "Ronald Holland II", "team": "DETROIT PISTONS"},
  "1628989": {"name": "Kevin Huerter", "team": "DETROIT PISTONS"},
  "1642450": {"name": "Daniss Jenkins", "team": "DETROIT PISTONS"},
  "1642403": {"name": "Isaac Jones", "team": "DETROIT PISTONS"},
  "1642404": {"name": "Chaz Lanier", "team": "DETROIT PISTONS"},
  "1627747": {"name": "Caris LeVert", "team": "DETROIT PISTONS"},
  "1631111": {"name": "Wendell Moore Jr.", "team": "DETROIT PISTONS"},
  "1630194": {"name": "Paul Reed", "team": "DETROIT PISTONS"},
  "1629130": {"name": "Duncan Robinson", "team": "DETROIT PISTONS"},
  "1631204": {"name": "Marcus Sasser", "team": "DETROIT PISTONS"},
  "1642449": {"name": "Tolu Smith", "team": "DETROIT PISTONS"},
  "1630191": {"name": "Isaiah Stewart", "team": "DETROIT PISTONS"},
  "1641709": {"name": "Ausar Thompson", "team": "DETROIT PISTONS"},
  "203500":  {"name": "Steven Adams", "team": "HOUSTON ROCKETS"},
  "203991":  {"name": "Clint Capela", "team": "HOUSTON ROCKETS"},
  "1642384": {"name": "Isaiah Crawford", "team": "HOUSTON ROCKETS"},
  "1631120": {"name": "JD Davison", "team": "HOUSTON ROCKETS"},
  "201142":  {"name": "Kevin Durant", "team": "HOUSTON ROCKETS"},
  "1631106": {"name": "Tari Eason", "team": "HOUSTON ROCKETS"},
  "1627827": {"name": "Dorian Finney-Smith", "team": "HOUSTON ROCKETS"},
  "201145":  {"name": "Jeff Green", "team": "HOUSTON ROCKETS"},
  "1628988": {"name": "Aaron Holiday", "team": "HOUSTON ROCKETS"},
  "1629006": {"name": "Josh Okogie", "team": "HOUSTON ROCKETS"},
  "1630578": {"name": "Alperen Sengun", "team": "HOUSTON ROCKETS"},
  "1642263": {"name": "Reed Sheppard", "team": "HOUSTON ROCKETS"},
  "1631095": {"name": "Jabari Smith Jr.", "team": "HOUSTON ROCKETS"},
  "1630256": {"name": "Jae'Sean Tate", "team": "HOUSTON ROCKETS"},
  "1641708": {"name": "Amen Thompson", "team": "HOUSTON ROCKETS"},
  "1627832": {"name": "Fred VanVleet", "team": "HOUSTON ROCKETS"},
  "1629028": {"name": "Deandre Ayton", "team": "LOS ANGELES LAKERS"},
  "1629029": {"name": "Luka Dončić", "team": "LOS ANGELES LAKERS"},
  "1629060": {"name": "Rui Hachimura", "team": "LOS ANGELES LAKERS"},
  "1629637": {"name": "Jaxson Hayes", "team": "LOS ANGELES LAKERS"},
  "1642355": {"name": "Bronny James", "team": "LOS ANGELES LAKERS"},
  "2544":    {"name": "LeBron James", "team": "LOS ANGELES LAKERS"},
  "1628379": {"name": "Luke Kennard", "team": "LOS ANGELES LAKERS"},
  "1628467": {"name": "Maxi Kleber", "team": "LOS ANGELES LAKERS"},
  "1642261": {"name": "Dalton Knecht", "team": "LOS ANGELES LAKERS"},
  "1631222": {"name": "Jake LaRavia", "team": "LOS ANGELES LAKERS"},
  "1643024": {"name": "Chris Mañon", "team": "LOS ANGELES LAKERS"},
  "1630559": {"name": "Austin Reaves", "team": "LOS ANGELES LAKERS"},
  "203935":  {"name": "Marcus Smart", "team": "LOS ANGELES LAKERS"},
  "1641733": {"name": "Nick Smith Jr.", "team": "LOS ANGELES LAKERS"},
  "1642876": {"name": "Adou Thiero", "team": "LOS ANGELES LAKERS"},
  "1629020": {"name": "Jarred Vanderbilt", "team": "LOS ANGELES LAKERS"},
  "203937":  {"name": "Kyle Anderson", "team": "MINNESOTA TIMBERWOLVES"},
  "1642866": {"name": "Joan Beringer", "team": "MINNESOTA TIMBERWOLVES"},
  "1641740": {"name": "Jaylen Clark", "team": "MINNESOTA TIMBERWOLVES"},
  "201144":  {"name": "Mike Conley", "team": "MINNESOTA TIMBERWOLVES"},
  "1628978": {"name": "Donte DiVincenzo", "team": "MINNESOTA TIMBERWOLVES"},
  "1630245": {"name": "Ayo Dosunmu", "team": "MINNESOTA TIMBERWOLVES"},
  "1630162": {"name": "Anthony Edwards", "team": "MINNESOTA TIMBERWOLVES"},
  "1642402": {"name": "Enrique Freeman", "team": "MINNESOTA TIMBERWOLVES"},
  "203497":  {"name": "Rudy Gobert", "team": "MINNESOTA TIMBERWOLVES"},
  "1630538": {"name": "Bones Hyland", "team": "MINNESOTA TIMBERWOLVES"},
  "204060":  {"name": "Joe Ingles", "team": "MINNESOTA TIMBERWOLVES"},
  "1630183": {"name": "Jaden McDaniels", "team": "MINNESOTA TIMBERWOLVES"},
  "1641763": {"name": "Julian Phillips", "team": "MINNESOTA TIMBERWOLVES"},
  "203944":  {"name": "Julius Randle", "team": "MINNESOTA TIMBERWOLVES"},
  "1629675": {"name": "Naz Reid", "team": "MINNESOTA TIMBERWOLVES"},
  "1630545": {"name": "Terrence Shannon Jr.", "team": "MINNESOTA TIMBERWOLVES"},
  "1642911": {"name": "Rocco Zikarsky", "team": "MINNESOTA TIMBERWOLVES"},
  "1630631": {"name": "Jose Alvarado", "team": "NEW YORK KNICKS"},
  "1628384": {"name": "OG Anunoby", "team": "NEW YORK KNICKS"},
  "1628969": {"name": "Mikal Bridges", "team": "NEW YORK KNICKS"},
  "1628973": {"name": "Jalen Brunson", "team": "NEW YORK KNICKS"},
  "203903":  {"name": "Jordan Clarkson", "team": "NEW YORK KNICKS"},
  "1642359": {"name": "Pacôme Dadiet", "team": "NEW YORK KNICKS"},
  "1642885": {"name": "Mohamed Diawara", "team": "NEW YORK KNICKS"},
  "1628404": {"name": "Josh Hart", "team": "NEW YORK KNICKS"},
  "1630574": {"name": "Ariel Hukporti", "team": "NEW YORK KNICKS"},
  "1641998": {"name": "Trey Jemison III", "team": "NEW YORK KNICKS"},
  "1642278": {"name": "Tyler Kolek", "team": "NEW YORK KNICKS"},
  "1630540": {"name": "Miles McBride", "team": "NEW YORK KNICKS"},
  "1641755": {"name": "Kevin McCullar Jr.", "team": "NEW YORK KNICKS"},
  "1629011": {"name": "Mitchell Robinson", "team": "NEW YORK KNICKS"},
  "1629013": {"name": "Landry Shamet", "team": "NEW YORK KNICKS"},
  "1631110": {"name": "Jeremy Sochan", "team": "NEW YORK KNICKS"},
  "1626157": {"name": "Karl-Anthony Towns", "team": "NEW YORK KNICKS"},
  "1642964": {"name": "Brooks Barnhizer", "team": "OKLAHOMA CITY THUNDER"},
  "1642382": {"name": "Branden Carlson", "team": "OKLAHOMA CITY THUNDER"},
  "1627936": {"name": "Alex Caruso", "team": "OKLAHOMA CITY THUNDER"},
  "1629652": {"name": "Luguentz Dort", "team": "OKLAHOMA CITY THUNDER"},
  "1628983": {"name": "Shai Gilgeous-Alexander", "team": "OKLAHOMA CITY THUNDER"},
  "1628392": {"name": "Isaiah Hartenstein", "team": "OKLAHOMA CITY THUNDER"},
  "1631096": {"name": "Chet Holmgren", "team": "OKLAHOMA CITY THUNDER"},
  "1630198": {"name": "Isaiah Joe", "team": "OKLAHOMA CITY THUNDER"},
  "1642272": {"name": "Jared McCain", "team": "OKLAHOMA CITY THUNDER"},
  "1642349": {"name": "Ajay Mitchell", "team": "OKLAHOMA CITY THUNDER"},
  "1642850": {"name": "Thomas Sorber", "team": "OKLAHOMA CITY THUNDER"},
  "1642260": {"name": "Nikola Topić", "team": "OKLAHOMA CITY THUNDER"},
  "1641717": {"name": "Cason Wallace", "team": "OKLAHOMA CITY THUNDER"},
  "1630598": {"name": "Aaron Wiggins", "team": "OKLAHOMA CITY THUNDER"},
  "1631114": {"name": "Jalen Williams", "team": "OKLAHOMA CITY THUNDER"},
  "1631119": {"name": "Jaylin Williams", "team": "OKLAHOMA CITY THUNDER"},
  "1629026": {"name": "Kenrich Williams", "team": "OKLAHOMA CITY THUNDER"},
  "1631094": {"name": "Paolo Banchero", "team": "ORLANDO MAGIC"},
  "1630217": {"name": "Desmond Bane", "team": "ORLANDO MAGIC"},
  "1629048": {"name": "Goga Bitadze", "team": "ORLANDO MAGIC"},
  "1641710": {"name": "Anthony Black", "team": "ORLANDO MAGIC"},
  "1631288": {"name": "Jamal Cain", "team": "ORLANDO MAGIC"},
  "1628975": {"name": "Jevon Carter", "team": "ORLANDO MAGIC"},
  "1628976": {"name": "Wendell Carter Jr.", "team": "ORLANDO MAGIC"},
  "1630658": {"name": "Colin Castleton", "team": "ORLANDO MAGIC"},
  "1630284": {"name": "Kevon Harris", "team": "ORLANDO MAGIC"},
  "1641724": {"name": "Jett Howard", "team": "ORLANDO MAGIC"},
  "1628371": {"name": "Jonathan Isaac", "team": "ORLANDO MAGIC"},
  "1642869": {"name": "Noah Penda", "team": "ORLANDO MAGIC"},
  "1642859": {"name": "Jase Richardson", "team": "ORLANDO MAGIC"},
  "1630591": {"name": "Jalen Suggs", "team": "ORLANDO MAGIC"},
  "1630532": {"name": "Franz Wagner", "team": "ORLANDO MAGIC"},
  "1629021": {"name": "Moritz Wagner", "team": "ORLANDO MAGIC"},
  "1641783": {"name": "Tristan da Silva", "team": "ORLANDO MAGIC"},
  "1631230": {"name": "Dominick Barlow", "team": "PHILADELPHIA 76ERS"},
  "1641737": {"name": "Adem Bona", "team": "PHILADELPHIA 76ERS"},
  "1641780": {"name": "Johni Broome", "team": "PHILADELPHIA 76ERS"},
  "203083":  {"name": "Andre Drummond", "team": "PHILADELPHIA 76ERS"},
  "1642845": {"name": "VJ Edgecombe", "team": "PHILADELPHIA 76ERS"},
  "1642348": {"name": "Justin Edwards", "team": "PHILADELPHIA 76ERS"},
  "203954":  {"name": "Joel Embiid", "team": "PHILADELPHIA 76ERS"},
  "202331":  {"name": "Paul George", "team": "PHILADELPHIA 76ERS"},
  "1629656": {"name": "Quentin Grimes", "team": "PHILADELPHIA 76ERS"},
  "200768":  {"name": "Kyle Lowry", "team": "PHILADELPHIA 76ERS"},
  "1631213": {"name": "Tyrese Martin", "team": "PHILADELPHIA 76ERS"},
  "1630178": {"name": "Tyrese Maxey", "team": "PHILADELPHIA 76ERS"},
  "1626162": {"name": "Kelly Oubre Jr.", "team": "PHILADELPHIA 76ERS"},
  "1631207": {"name": "Dalen Terry", "team": "PHILADELPHIA 76ERS"},
  "1631133": {"name": "Jabari Walker", "team": "PHILADELPHIA 76ERS"},
  "1630570": {"name": "Trendon Watford", "team": "PHILADELPHIA 76ERS"},
  "1628960": {"name": "Grayson Allen", "team": "PHOENIX SUNS"},
  "1626164": {"name": "Devin Booker", "team": "PHOENIX SUNS"},
  "1642886": {"name": "Koby Brea", "team": "PHOENIX SUNS"},
  "1628415": {"name": "Dillon Brooks", "team": "PHOENIX SUNS"},
  "1629599": {"name": "Amir Coffey", "team": "PHOENIX SUNS"},
  "1642346": {"name": "Ryan Dunn", "team": "PHOENIX SUNS"},
  "1642853": {"name": "Rasheer Fleming", "team": "PHOENIX SUNS"},
  "1631221": {"name": "Collin Gillespie", "team": "PHOENIX SUNS"},
  "1630692": {"name": "Jordan Goodwin", "team": "PHOENIX SUNS"},
  "1630224": {"name": "Jalen Green", "team": "PHOENIX SUNS"},
  "1629312": {"name": "Haywood Highsmith", "team": "PHOENIX SUNS"},
  "1643047": {"name": "CJ Huntley", "team": "PHOENIX SUNS"},
  "1642345": {"name": "Oso Ighodaro", "team": "PHOENIX SUNS"},
  "1630587": {"name": "Isaiah Livers", "team": "PHOENIX SUNS"},
  "1642863": {"name": "Khaman Maluach", "team": "PHOENIX SUNS"},
  "1626220": {"name": "Royce O'Neale", "team": "PHOENIX SUNS"},
  "1631109": {"name": "Mark Williams", "team": "PHOENIX SUNS"},
  "1630166": {"name": "Deni Avdija", "team": "PORTLAND TRAIL BLAZERS"},
  "1641739": {"name": "Toumani Camara", "team": "PORTLAND TRAIL BLAZERS"},
  "1631321": {"name": "Sidy Cissoko", "team": "PORTLAND TRAIL BLAZERS"},
  "1642270": {"name": "Donovan Clingan", "team": "PORTLAND TRAIL BLAZERS"},
  "203924":  {"name": "Jerami Grant", "team": "PORTLAND TRAIL BLAZERS"},
  "1630703": {"name": "Scoot Henderson", "team": "PORTLAND TRAIL BLAZERS"},
  "201950":  {"name": "Jrue Holiday", "team": "PORTLAND TRAIL BLAZERS"},
  "1630249": {"name": "Vít Krejčí", "team": "PORTLAND TRAIL BLAZERS"},
  "203081":  {"name": "Damian Lillard", "team": "PORTLAND TRAIL BLAZERS"},
  "1631126": {"name": "Caleb Love", "team": "PORTLAND TRAIL BLAZERS"},
  "1631200": {"name": "Kris Murray", "team": "PORTLAND TRAIL BLAZERS"},
  "1631101": {"name": "Shaedon Sharpe", "team": "PORTLAND TRAIL BLAZERS"},
  "1629680": {"name": "Matisse Thybulle", "team": "PORTLAND TRAIL BLAZERS"},
  "1631104": {"name": "Blake Wesley", "team": "PORTLAND TRAIL BLAZERS"},
  "1629057": {"name": "Robert Williams III", "team": "PORTLAND TRAIL BLAZERS"},
  "1642905": {"name": "Yang Hansen", "team": "PORTLAND TRAIL BLAZERS"},
  "1642959": {"name": "Chris Youngblood", "team": "PORTLAND TRAIL BLAZERS"},
  "203084":  {"name": "Harrison Barnes", "team": "SAN ANTONIO SPURS"},
  "202687":  {"name": "Bismack Biyombo", "team": "SAN ANTONIO SPURS"},
  "1642868": {"name": "Carter Bryant", "team": "SAN ANTONIO SPURS"},
  "1642264": {"name": "Stephon Castle", "team": "SAN ANTONIO SPURS"},
  "1630577": {"name": "Julian Champagnie", "team": "SAN ANTONIO SPURS"},
  "1628368": {"name": "De'Aaron Fox", "team": "SAN ANTONIO SPURS"},
  "1642844": {"name": "Dylan Harper", "team": "SAN ANTONIO SPURS"},
  "1631127": {"name": "Harrison Ingram", "team": "SAN ANTONIO SPURS"},
  "1629640": {"name": "Keldon Johnson", "team": "SAN ANTONIO SPURS"},
  "1642357": {"name": "David Jones Garcia", "team": "SAN ANTONIO SPURS"},
  "1628436": {"name": "Luke Kornet", "team": "SAN ANTONIO SPURS"},
  "1629162": {"name": "Jordan McLaughlin", "team": "SAN ANTONIO SPURS"},
  "1641801": {"name": "Emanuel Miller", "team": "SAN ANTONIO SPURS"},
  "203482":  {"name": "Kelly Olynyk", "team": "SAN ANTONIO SPURS"},
  "203486":  {"name": "Mason Plumlee", "team": "SAN ANTONIO SPURS"},
  "1630170": {"name": "Devin Vassell", "team": "SAN ANTONIO SPURS"},
  "1630322": {"name": "Lindy Waters III", "team": "SAN ANTONIO SPURS"},
  "1641705": {"name": "Victor Wembanyama", "team": "SAN ANTONIO SPURS"},
  "1630567": {"name": "Scottie Barnes", "team": "TORONTO RAPTORS"},
  "1629628": {"name": "RJ Barrett", "team": "TORONTO RAPTORS"},
  "1642419": {"name": "Jamison Battle", "team": "TORONTO RAPTORS"},
  "1641711": {"name": "Gradey Dick", "team": "TORONTO RAPTORS"},
  "1642935": {"name": "Chucky Hepburn", "team": "TORONTO RAPTORS"},
  "1627742": {"name": "Brandon Ingram", "team": "TORONTO RAPTORS"},
  "1631218": {"name": "Trayce Jackson-Davis", "team": "TORONTO RAPTORS"},
  "1630639": {"name": "A.J. Lawson", "team": "TORONTO RAPTORS"},
  "1630572": {"name": "Sandro Mamukelashvili", "team": "TORONTO RAPTORS"},
  "1642918": {"name": "Alijah Martin", "team": "TORONTO RAPTORS"},
  "1642367": {"name": "Jonathan Mogbo", "team": "TORONTO RAPTORS"},
  "1642867": {"name": "Collin Murray-Boyles", "team": "TORONTO RAPTORS"},
  "1627751": {"name": "Jakob Poeltl", "team": "TORONTO RAPTORS"},
  "1630193": {"name": "Immanuel Quickley", "team": "TORONTO RAPTORS"},
  "1642347": {"name": "Jamal Shead", "team": "TORONTO RAPTORS"},
  "202066":  {"name": "Garrett Temple", "team": "TORONTO RAPTORS"},
  "1642266": {"name": "Ja'Kobe Walter", "team": "TORONTO RAPTORS"}
}

def fetch_injuries():
    url = "https://tank01-fantasy-stats.p.rapidapi.com/getNBAInjuryList"
    headers = {
        "x-rapidapi-key": RAPIDAPI_KEY,
        "x-rapidapi-host": "tank01-fantasy-stats.p.rapidapi.com"
    }
    r = requests.get(url, headers=headers, timeout=15)
    r.raise_for_status()
    return r.json()

def main():
    print("Fetching injury list...")
    data = fetch_injuries()
    body = data.get("body", [])
    print(f"Total blessés dans l'API : {len(body)}")
    if body:
        print("Exemple premier joueur :")
        import json
        print(json.dumps(body[0], indent=2))
    with open("injuries.json", "w", encoding="utf-8") as f:
        json.dump({"debug": body[:3]}, f, ensure_ascii=False, indent=2)
