import requests
import json
import os
import unicodedata
from datetime import datetime

RAPIDAPI_KEY = os.environ.get("RAPIDAPI_KEY", "")

PLAYER_MAP = {
  "Nickeil Alexander-Walker": "ATLANTA HAWKS",
  "Tony Bradley": "ATLANTA HAWKS",
  "Dyson Daniels": "ATLANTA HAWKS",
  "RayJ Dennis": "ATLANTA HAWKS",
  "Mouhamed Gueye": "ATLANTA HAWKS",
  "Buddy Hield": "ATLANTA HAWKS",
  "Jalen Johnson": "ATLANTA HAWKS",
  "Corey Kispert": "ATLANTA HAWKS",
  "Christian Koloko": "ATLANTA HAWKS",
  "Jonathan Kuminga": "ATLANTA HAWKS",
  "Jock Landale": "ATLANTA HAWKS",
  "CJ McCollum": "ATLANTA HAWKS",
  "Asa Newell": "ATLANTA HAWKS",
  "Georges Niang": "ATLANTA HAWKS",
  "Onyeka Okongwu": "ATLANTA HAWKS",
  "Zaccharie Risacher": "ATLANTA HAWKS",
  "Gabe Vincent": "ATLANTA HAWKS",
  "Keaton Wallace": "ATLANTA HAWKS",
  "Jaylen Brown": "BOSTON CELTICS",
  "Luka Garza": "BOSTON CELTICS",
  "Hugo Gonzalez": "BOSTON CELTICS",
  "Ron Harper Jr.": "BOSTON CELTICS",
  "Sam Hauser": "BOSTON CELTICS",
  "Payton Pritchard": "BOSTON CELTICS",
  "Neemias Queta": "BOSTON CELTICS",
  "Baylor Scheierman": "BOSTON CELTICS",
  "Max Shulga": "BOSTON CELTICS",
  "Jayson Tatum": "BOSTON CELTICS",
  "John Tonje": "BOSTON CELTICS",
  "Nikola Vucevic": "BOSTON CELTICS",
  "Jordan Walsh": "BOSTON CELTICS",
  "Derrick White": "BOSTON CELTICS",
  "Amari Williams": "BOSTON CELTICS",
  "Jarrett Allen": "CLEVELAND CAVALIERS",
  "Thomas Bryant": "CLEVELAND CAVALIERS",
  "Keon Ellis": "CLEVELAND CAVALIERS",
  "James Harden": "CLEVELAND CAVALIERS",
  "Sam Merrill": "CLEVELAND CAVALIERS",
  "Riley Minix": "CLEVELAND CAVALIERS",
  "Donovan Mitchell": "CLEVELAND CAVALIERS",
  "Evan Mobley": "CLEVELAND CAVALIERS",
  "Larry Nance Jr.": "CLEVELAND CAVALIERS",
  "Craig Porter Jr.": "CLEVELAND CAVALIERS",
  "Tyrese Proctor": "CLEVELAND CAVALIERS",
  "Dennis Schroder": "CLEVELAND CAVALIERS",
  "Max Strus": "CLEVELAND CAVALIERS",
  "Nae'Qwan Tomlin": "CLEVELAND CAVALIERS",
  "Jaylon Tyson": "CLEVELAND CAVALIERS",
  "Dean Wade": "CLEVELAND CAVALIERS",
  "Christian Braun": "DENVER NUGGETS",
  "Bruce Brown": "DENVER NUGGETS",
  "Aaron Gordon": "DENVER NUGGETS",
  "Tim Hardaway Jr.": "DENVER NUGGETS",
  "DaRon Holmes II": "DENVER NUGGETS",
  "Cameron Johnson": "DENVER NUGGETS",
  "Nikola Jokic": "DENVER NUGGETS",
  "Curtis Jones": "DENVER NUGGETS",
  "Spencer Jones": "DENVER NUGGETS",
  "Tyus Jones": "DENVER NUGGETS",
  "Jamal Murray": "DENVER NUGGETS",
  "Zeke Nnaji": "DENVER NUGGETS",
  "Jalen Pickett": "DENVER NUGGETS",
  "KJ Simpson": "DENVER NUGGETS",
  "Julian Strawther": "DENVER NUGGETS",
  "Jonas Valanciunas": "DENVER NUGGETS",
  "Peyton Watson": "DENVER NUGGETS",
  "Cade Cunningham": "DETROIT PISTONS",
  "Jalen Duren": "DETROIT PISTONS",
  "Javonte Green": "DETROIT PISTONS",
  "Tobias Harris": "DETROIT PISTONS",
  "Ronald Holland II": "DETROIT PISTONS",
  "Kevin Huerter": "DETROIT PISTONS",
  "Daniss Jenkins": "DETROIT PISTONS",
  "Isaac Jones": "DETROIT PISTONS",
  "Chaz Lanier": "DETROIT PISTONS",
  "Caris LeVert": "DETROIT PISTONS",
  "Wendell Moore Jr.": "DETROIT PISTONS",
  "Paul Reed": "DETROIT PISTONS",
  "Duncan Robinson": "DETROIT PISTONS",
  "Marcus Sasser": "DETROIT PISTONS",
  "Tolu Smith": "DETROIT PISTONS",
  "Isaiah Stewart": "DETROIT PISTONS",
  "Ausar Thompson": "DETROIT PISTONS",
  "Steven Adams": "HOUSTON ROCKETS",
  "Clint Capela": "HOUSTON ROCKETS",
  "Isaiah Crawford": "HOUSTON ROCKETS",
  "JD Davison": "HOUSTON ROCKETS",
  "Kevin Durant": "HOUSTON ROCKETS",
  "Tari Eason": "HOUSTON ROCKETS",
  "Dorian Finney-Smith": "HOUSTON ROCKETS",
  "Jeff Green": "HOUSTON ROCKETS",
  "Aaron Holiday": "HOUSTON ROCKETS",
  "Josh Okogie": "HOUSTON ROCKETS",
  "Alperen Sengun": "HOUSTON ROCKETS",
  "Reed Sheppard": "HOUSTON ROCKETS",
  "Jabari Smith Jr.": "HOUSTON ROCKETS",
  "Jae'Sean Tate": "HOUSTON ROCKETS",
  "Amen Thompson": "HOUSTON ROCKETS",
  "Fred VanVleet": "HOUSTON ROCKETS",
  "Deandre Ayton": "LOS ANGELES LAKERS",
  "Luka Doncic": "LOS ANGELES LAKERS",
  "Rui Hachimura": "LOS ANGELES LAKERS",
  "Jaxson Hayes": "LOS ANGELES LAKERS",
  "Bronny James": "LOS ANGELES LAKERS",
  "LeBron James": "LOS ANGELES LAKERS",
  "Luke Kennard": "LOS ANGELES LAKERS",
  "Maxi Kleber": "LOS ANGELES LAKERS",
  "Dalton Knecht": "LOS ANGELES LAKERS",
  "Jake LaRavia": "LOS ANGELES LAKERS",
  "Chris Manon": "LOS ANGELES LAKERS",
  "Austin Reaves": "LOS ANGELES LAKERS",
  "Marcus Smart": "LOS ANGELES LAKERS",
  "Nick Smith Jr.": "LOS ANGELES LAKERS",
  "Adou Thiero": "LOS ANGELES LAKERS",
  "Jarred Vanderbilt": "LOS ANGELES LAKERS",
  "Kyle Anderson": "MINNESOTA TIMBERWOLVES",
  "Joan Beringer": "MINNESOTA TIMBERWOLVES",
  "Jaylen Clark": "MINNESOTA TIMBERWOLVES",
  "Mike Conley": "MINNESOTA TIMBERWOLVES",
  "Donte DiVincenzo": "MINNESOTA TIMBERWOLVES",
  "Ayo Dosunmu": "MINNESOTA TIMBERWOLVES",
  "Anthony Edwards": "MINNESOTA TIMBERWOLVES",
  "Enrique Freeman": "MINNESOTA TIMBERWOLVES",
  "Rudy Gobert": "MINNESOTA TIMBERWOLVES",
  "Bones Hyland": "MINNESOTA TIMBERWOLVES",
  "Joe Ingles": "MINNESOTA TIMBERWOLVES",
  "Jaden McDaniels": "MINNESOTA TIMBERWOLVES",
  "Julian Phillips": "MINNESOTA TIMBERWOLVES",
  "Julius Randle": "MINNESOTA TIMBERWOLVES",
  "Naz Reid": "MINNESOTA TIMBERWOLVES",
  "Terrence Shannon Jr.": "MINNESOTA TIMBERWOLVES",
  "Rocco Zikarsky": "MINNESOTA TIMBERWOLVES",
  "Jose Alvarado": "NEW YORK KNICKS",
  "OG Anunoby": "NEW YORK KNICKS",
  "Mikal Bridges": "NEW YORK KNICKS",
  "Jalen Brunson": "NEW YORK KNICKS",
  "Jordan Clarkson": "NEW YORK KNICKS",
  "Pacome Dadiet": "NEW YORK KNICKS",
  "Mohamed Diawara": "NEW YORK KNICKS",
  "Josh Hart": "NEW YORK KNICKS",
  "Ariel Hukporti": "NEW YORK KNICKS",
  "Trey Jemison III": "NEW YORK KNICKS",
  "Tyler Kolek": "NEW YORK KNICKS",
  "Miles McBride": "NEW YORK KNICKS",
  "Kevin McCullar Jr.": "NEW YORK KNICKS",
  "Mitchell Robinson": "NEW YORK KNICKS",
  "Landry Shamet": "NEW YORK KNICKS",
  "Jeremy Sochan": "NEW YORK KNICKS",
  "Karl-Anthony Towns": "NEW YORK KNICKS",
  "Brooks Barnhizer": "OKLAHOMA CITY THUNDER",
  "Branden Carlson": "OKLAHOMA CITY THUNDER",
  "Alex Caruso": "OKLAHOMA CITY THUNDER",
  "Luguentz Dort": "OKLAHOMA CITY THUNDER",
  "Shai Gilgeous-Alexander": "OKLAHOMA CITY THUNDER",
  "Isaiah Hartenstein": "OKLAHOMA CITY THUNDER",
  "Chet Holmgren": "OKLAHOMA CITY THUNDER",
  "Isaiah Joe": "OKLAHOMA CITY THUNDER",
  "Jared McCain": "OKLAHOMA CITY THUNDER",
  "Ajay Mitchell": "OKLAHOMA CITY THUNDER",
  "Thomas Sorber": "OKLAHOMA CITY THUNDER",
  "Nikola Topic": "OKLAHOMA CITY THUNDER",
  "Cason Wallace": "OKLAHOMA CITY THUNDER",
  "Aaron Wiggins": "OKLAHOMA CITY THUNDER",
  "Jalen Williams": "OKLAHOMA CITY THUNDER",
  "Jaylin Williams": "OKLAHOMA CITY THUNDER",
  "Kenrich Williams": "OKLAHOMA CITY THUNDER",
  "Paolo Banchero": "ORLANDO MAGIC",
  "Desmond Bane": "ORLANDO MAGIC",
  "Goga Bitadze": "ORLANDO MAGIC",
  "Anthony Black": "ORLANDO MAGIC",
  "Jamal Cain": "ORLANDO MAGIC",
  "Jevon Carter": "ORLANDO MAGIC",
  "Wendell Carter Jr.": "ORLANDO MAGIC",
  "Colin Castleton": "ORLANDO MAGIC",
  "Kevon Harris": "ORLANDO MAGIC",
  "Jett Howard": "ORLANDO MAGIC",
  "Jonathan Isaac": "ORLANDO MAGIC",
  "Noah Penda": "ORLANDO MAGIC",
  "Jase Richardson": "ORLANDO MAGIC",
  "Jalen Suggs": "ORLANDO MAGIC",
  "Franz Wagner": "ORLANDO MAGIC",
  "Moritz Wagner": "ORLANDO MAGIC",
  "Tristan da Silva": "ORLANDO MAGIC",
  "Dominick Barlow": "PHILADELPHIA 76ERS",
  "Adem Bona": "PHILADELPHIA 76ERS",
  "Johni Broome": "PHILADELPHIA 76ERS",
  "Andre Drummond": "PHILADELPHIA 76ERS",
  "VJ Edgecombe": "PHILADELPHIA 76ERS",
  "Justin Edwards": "PHILADELPHIA 76ERS",
  "Joel Embiid": "PHILADELPHIA 76ERS",
  "Paul George": "PHILADELPHIA 76ERS",
  "Quentin Grimes": "PHILADELPHIA 76ERS",
  "Kyle Lowry": "PHILADELPHIA 76ERS",
  "Tyrese Martin": "PHILADELPHIA 76ERS",
  "Tyrese Maxey": "PHILADELPHIA 76ERS",
  "Kelly Oubre Jr.": "PHILADELPHIA 76ERS",
  "Dalen Terry": "PHILADELPHIA 76ERS",
  "Jabari Walker": "PHILADELPHIA 76ERS",
  "Trendon Watford": "PHILADELPHIA 76ERS",
  "Grayson Allen": "PHOENIX SUNS",
  "Devin Booker": "PHOENIX SUNS",
  "Koby Brea": "PHOENIX SUNS",
  "Dillon Brooks": "PHOENIX SUNS",
  "Amir Coffey": "PHOENIX SUNS",
  "Ryan Dunn": "PHOENIX SUNS",
  "Rasheer Fleming": "PHOENIX SUNS",
  "Collin Gillespie": "PHOENIX SUNS",
  "Jordan Goodwin": "PHOENIX SUNS",
  "Jalen Green": "PHOENIX SUNS",
  "Haywood Highsmith": "PHOENIX SUNS",
  "CJ Huntley": "PHOENIX SUNS",
  "Oso Ighodaro": "PHOENIX SUNS",
  "Isaiah Livers": "PHOENIX SUNS",
  "Khaman Maluach": "PHOENIX SUNS",
  "Royce O'Neale": "PHOENIX SUNS",
  "Mark Williams": "PHOENIX SUNS",
  "Deni Avdija": "PORTLAND TRAIL BLAZERS",
  "Toumani Camara": "PORTLAND TRAIL BLAZERS",
  "Sidy Cissoko": "PORTLAND TRAIL BLAZERS",
  "Donovan Clingan": "PORTLAND TRAIL BLAZERS",
  "Jerami Grant": "PORTLAND TRAIL BLAZERS",
  "Scoot Henderson": "PORTLAND TRAIL BLAZERS",
  "Jrue Holiday": "PORTLAND TRAIL BLAZERS",
  "Vit Krejci": "PORTLAND TRAIL BLAZERS",
  "Damian Lillard": "PORTLAND TRAIL BLAZERS",
  "Caleb Love": "PORTLAND TRAIL BLAZERS",
  "Kris Murray": "PORTLAND TRAIL BLAZERS",
  "Shaedon Sharpe": "PORTLAND TRAIL BLAZERS",
  "Matisse Thybulle": "PORTLAND TRAIL BLAZERS",
  "Blake Wesley": "PORTLAND TRAIL BLAZERS",
  "Robert Williams III": "PORTLAND TRAIL BLAZERS",
  "Yang Hansen": "PORTLAND TRAIL BLAZERS",
  "Chris Youngblood": "PORTLAND TRAIL BLAZERS",
  "Harrison Barnes": "SAN ANTONIO SPURS",
  "Bismack Biyombo": "SAN ANTONIO SPURS",
  "Carter Bryant": "SAN ANTONIO SPURS",
  "Stephon Castle": "SAN ANTONIO SPURS",
  "Julian Champagnie": "SAN ANTONIO SPURS",
  "De'Aaron Fox": "SAN ANTONIO SPURS",
  "Dylan Harper": "SAN ANTONIO SPURS",
  "Harrison Ingram": "SAN ANTONIO SPURS",
  "Keldon Johnson": "SAN ANTONIO SPURS",
  "David Jones Garcia": "SAN ANTONIO SPURS",
  "Luke Kornet": "SAN ANTONIO SPURS",
  "Jordan McLaughlin": "SAN ANTONIO SPURS",
  "Emanuel Miller": "SAN ANTONIO SPURS",
  "Kelly Olynyk": "SAN ANTONIO SPURS",
  "Mason Plumlee": "SAN ANTONIO SPURS",
  "Devin Vassell": "SAN ANTONIO SPURS",
  "Lindy Waters III": "SAN ANTONIO SPURS",
  "Victor Wembanyama": "SAN ANTONIO SPURS",
  "Scottie Barnes": "TORONTO RAPTORS",
  "RJ Barrett": "TORONTO RAPTORS",
  "Jamison Battle": "TORONTO RAPTORS",
  "Gradey Dick": "TORONTO RAPTORS",
  "Chucky Hepburn": "TORONTO RAPTORS",
  "Brandon Ingram": "TORONTO RAPTORS",
  "Trayce Jackson-Davis": "TORONTO RAPTORS",
  "A.J. Lawson": "TORONTO RAPTORS",
  "Sandro Mamukelashvili": "TORONTO RAPTORS",
  "Alijah Martin": "TORONTO RAPTORS",
  "Jonathan Mogbo": "TORONTO RAPTORS",
  "Collin Murray-Boyles": "TORONTO RAPTORS",
  "Jakob Poeltl": "TORONTO RAPTORS",
  "Immanuel Quickley": "TORONTO RAPTORS",
  "Jamal Shead": "TORONTO RAPTORS",
  "Garrett Temple": "TORONTO RAPTORS",
  "Ja'Kobe Walter": "TORONTO RAPTORS"
}

def normalize(name):
    n = unicodedata.normalize("NFD", name)
    n = "".join(c for c in n if unicodedata.category(c) != "Mn")
    return n.strip().lower()

PLAYER_MAP_NORMALIZED = {normalize(k): (k, v) for k, v in PLAYER_MAP.items()}

def fetch_injuries():
    url = "https://tank01-fantasy-stats.p.rapidapi.com/getNBAInjuryList"
    headers = {
        "x-rapidapi-key": RAPIDAPI_KEY,
        "x-rapidapi-host": "tank01-fantasy-stats.p.rapidapi.com"
    }
    r = requests.get(url, headers=headers, timeout=15)
    r.raise_for_status()
    return r.json()

def main():
    print("Fetching injury list...")
    data = fetch_injuries()
    body = data.get("body", [])
    print(f"Total blessés dans l'API : {len(body)}")

    injuries = []
    for entry in body:
        raw_name = entry.get("longName", entry.get("name", ""))
        key = normalize(raw_name)
        if key not in PLAYER_MAP_NORMALIZED:
            continue
        original_name, team = PLAYER_MAP_NORMALIZED[key]
        injuries.append({
            "name": original_name,
            "team": team,
            "status": entry.get("designation", entry.get("injuryStatus", "?")),
            "description": entry.get("description", ""),
            "return_date": entry.get("injReturnDate", ""),
        })

    output = {
        "updated_at": datetime.utcnow().strftime("%d/%m/%Y %H:%M UTC"),
        "count": len(injuries),
        "injuries": injuries
    }
    with open("injuries.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"Done. {len(injuries)} blessé(s) dans notre liste.")

if __name__ == "__main__":
    main()
